import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import SideMenu from "./(components)/SideMenu";
import { AuthProvider } from "./Context/AuthContext";
import Header from "./(components)/Header";
import Footer from "./(components)/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EasyTrips",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
    <html  data-theme="light" lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      <Toaster />
      <SideMenu />
      <Footer />
      </body>
    </html>
    </AuthProvider>
  );
}
